#REMOVE APPS DEFAULT SYSTEM
Get-AppxPackage -allusers Microsoft.549981C3F5F10 | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.Windows.CloudExperienceHost | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.BingWeather | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.MicrosoftOfficeHub | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.MicrosoftSolitaireCollection | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.MicrosoftStickyNotes | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.Office.OneNote | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.People | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.SkypeApp | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.StorePurchaseApp | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.Wallet | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.WindowsAlarms | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.WindowsFeedbackHub | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.WindowsMaps | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.Xbox.TCUI | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.XboxApp | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.XboxGameOverlay | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.XboxGamingOverlay | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.XboxIdentityProvider | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.XboxSpeechToTextOverlay | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.YourPhone | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.ZuneMusic | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.ZuneVideo | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.MicrosoftEdgeDevToolsClient | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.Windows.ParentalControls | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.Windows.Search | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.XboxGameCallableUI | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.Windows.CloudExperienceHost | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.Windows.PeopleExperienceHost | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.Windows.SecHealthUI | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.Copilot | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.Windows.ParentalControls | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.MixedReality.Portal | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.GetHelp | Remove-AppxPackage
Get-AppxPackage -allusers MicrosoftWindows.UndockedDevKit | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.Windows.SecureAssessmentBrowser | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.Windows.SecHealthUI | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.Windows.NarratorQuickStart | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.Windows.ContentDeliveryManager | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.LockApp | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.ECApp  | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.CredDialogHost | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.AsyncTextService | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.BioEnrollment | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.AccountsControl | Remove-AppxPackage
Get-AppxPackage -allusers NcsiUwpApp | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.Windows.PinningConfirmationDialog | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.Windows.CallingShellApp | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.Windows.AssignedAccessLockApp | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.Windows.Apprep.ChxApp | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.AAD.BrokerPlugin | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.WindowsStore | Remove-AppxPackage
Get-AppxPackage -allusers microsoft.windowscommunicationsapps | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.Microsoft3DViewer | Remove-AppxPackage
Get-AppxPackage -allusers Microsoft.DesktopAppInstaller | Remove-AppxPackage
